name: Continuos Deployment

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  build-and-deploy:
    if: ${{ github.ref == 'refs/heads/development' }}
    name: Deployment in (DEV)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #Steps to build and deploy the app